#!/bin/bash

BASEDIR=`dirname $0`
templates=`ls $BASEDIR/sphinx/locale`
for t in $templates
do
	pofiles=`find $BASEDIR/sphinx/locale/$t -maxdepth 1 -type f -name '*.po'`
	for pofile in $pofiles
	do
		pofile=`basename $pofile`
		msgmerge -vU $BASEDIR/sphinx/locale/$t/$pofile $BASEDIR/sphinx/locale/$t/$t.pot
	done
done
